compile:
	cd /Users/park/code/smart-contract && npx hardhat compile

deploy:
	cd /Users/park/code/smart-contract && npx hardhat run scripts/deployVault.ts --network ganache
	cd /Users/park/code/smart-contract && npx hardhat run scripts/deployValidator.ts --network ganache 